# Generated by Django 4.1.1 on 2023-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_kullanici_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
