# Generated by Django 4.1.1 on 2023-10-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_kullanici_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='tel',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
