# Generated by Django 4.1.1 on 2023-10-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_kategori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
